<?php

namespace AppBundle\Repository;

/**
 * CvProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CvProjectRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT p
                      FROM AppBundle:CvProject p
                      JOIN AppBundle:Cv cv
                      WHERE p.cvId = cv.id
                      ORDER BY p.id ASC'
            )
            ->getResult();
    }
}
