<?php

namespace AppBundle\Repository;

/**
 * ExperienceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT e
                      FROM AppBundle:Experience e
                      JOIN AppBundle:Cv cv
                      WHERE e.cvId = cv.id
                      ORDER BY e.date DESC'
            )
            ->getResult();
    }
}
