<?php

namespace AppBundle\Repository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllData()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT s
                      FROM AppBundle:Skill s
                      JOIN AppBundle:Cv cv
                      WHERE s.cvId = cv.id
                      ORDER BY s.niv DESC'
            )
            ->getResult();
    }
}
